version: "3.9"
services:
  gateway:
    tty: true
    build:
      context: ./apps/gateway
      dockerfile: .docker/dev/Dockerfile
    command: ["npm", "run", "start:dev"]
    volumes:
      - ./apps/gateway:/usr/src/app:rw
      - /usr/src/app/node_modules
    ports:
      - 8888:8888
