##write a deployment file for gateway service

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: 317884193661.dkr.ecr.eu-west-1.amazonaws.com/isolates:42889a1659f1888bc2e95cf8b49da68fa5f3dd02
        ports:
        - containerPort: 8889
        env:
        - name: LOGIN_SERVICE_BASE_URI
          value: "http://login-service:8888"
        resources:
          limits:
            memory: "512Mi"
            cpu: "1000m"
          requests:
            memory: "256Mi"
            cpu: "500m"
