apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway-ingress
spec:
  rules:
  - host: af710e3861a694922a7788c89ce10ac7-e41f815623c9be81.elb.eu-west-1.amazonaws.com
    http:
      paths:
      - path: /graphql
        pathType: Prefix
        backend:
          service:
            name: gateway-service
            port:
              number: 80