name: Gateway Test and lint

on:
  push:
    branches:
      - '*'

jobs:
  gateway-test:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v2

      # Build the Docker image
      - name: Build the image
        run: |
          docker-compose build -t gateway .

      # Run tests in a Docker container
      - name: Run tests
        run: |
          docker-compose run gateway npm test

  gateway-lint:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v2

      # Build the Docker image
      - name: Build the image
        run: |
          docker-compose build -t app .

      # Run linting in a Docker container
      - name: Run linting
        run: |
          docker-compose run gateway npm run lint